added images flush and removed useless gc.dispose
zDevelopers/ImageOnMap pull request #119
Opened 2020-07-23 02:11 UTC by Vlammar

Add a give command, work also for command block or console. But does not support yet map name with spaces

2020-08-17 20:38 UTC, AmauryCarrade requested changes
Quelque remarques sur le code. Y'a pas mal de choses pas du tout liées à la commande `give`, d'ailleurs.

En terme d'UX, la commande n'est pas super triviale à utiliser… mais je ne vois pas trop comment faire mieux, si ce n'est ce qu'est possible actuellement, à savoir donner une carte qu'on a récupéré de notre inventaire.

Sauf à permettre d'ouvrir le GUI de quelqu'un d'autre.

2020-08-17 20:38 UTC, AmauryCarrade commented on src/main/java/fr/moribus/imageonmap/commands/maptool/GiveCommand.java
> +        final Player p= Bukkit.getPlayer(args[0]);
```suggestion
        final Player p = getPlayerParameter(0);
```

2020-08-17 20:38 UTC, AmauryCarrade commented on src/main/java/fr/moribus/imageonmap/commands/maptool/GiveCommand.java
> +                player = Bukkit.getPlayer(args[2]);
```suggestion
                player = getPlayerParameter(2);
```

2020-08-17 20:38 UTC, AmauryCarrade commented on src/main/java/fr/moribus/imageonmap/commands/maptool/GiveCommand.java
> +            }
Déjà géré par `getPlayerParameter`.

```suggestion
```

2020-08-17 20:38 UTC, AmauryCarrade commented on src/main/java/fr/moribus/imageonmap/commands/maptool/GiveCommand.java
> +                return;
```suggestion
                throwInvalidArgument(I.t("Map not found"));
```

2020-08-17 20:38 UTC, AmauryCarrade commented on src/main/java/fr/moribus/imageonmap/commands/maptool/GiveCommand.java
> +                }
Déjà géré par `getPlayerParameter`.

```suggestion
```

2020-08-17 20:38 UTC, AmauryCarrade commented on src/main/java/fr/moribus/imageonmap/image/ImageRendererExecutor.java
> +                if (url.toString().startsWith("https://imgur.com/")) {
```suggestion
                if (url.toString().toLowerCase().startsWith("https://imgur.com/")) {
```

2020-08-17 20:38 UTC, AmauryCarrade commented on src/main/java/fr/moribus/imageonmap/image/ImageRendererExecutor.java
> +        ImageIOExecutor.saveImage(mapID,image);
Pourquoi c'était commenté ? :thinking:

2020-08-17 20:38 UTC, AmauryCarrade commented on src/main/java/fr/moribus/imageonmap/image/ImageRendererExecutor.java
> +        poster.getImage().flush();//Safe?
Safe?

2020-08-17 20:38 UTC, AmauryCarrade commented on src/main/java/fr/moribus/imageonmap/image/ImageUtils.java
> +//import java.awt.*;
Code commenté à retirer.

2020-08-17 20:38 UTC, AmauryCarrade commented on src/main/java/fr/moribus/imageonmap/image/ImageUtils.java
> +            throw e;
Intérêt ?

2020-08-17 20:38 UTC, AmauryCarrade commented on src/main/java/fr/moribus/imageonmap/image/PosterImage.java
> +            throw e;}
Préférer un `try ... finally` ?

2020-08-17 21:42 UTC, Vlammar commented on src/main/java/fr/moribus/imageonmap/image/ImageRendererExecutor.java
> +        poster.getImage().flush();//Safe?
Je suis pas sûr de moi sur ce point, normalement on n'utilise plus l'image du poster après.

2020-08-17 21:44 UTC, Vlammar commented on src/main/java/fr/moribus/imageonmap/image/ImageUtils.java
> +//import java.awt.*;
La ligne import java.awt.*; est inutile, on utilise que BufferedImage de mémoire

2020-08-17 21:48 UTC, Vlammar commented on src/main/java/fr/moribus/imageonmap/image/ImageUtils.java
> +            throw e;
Aucun, c'était utilisé en cas d'erreur pour s'assurer que l'on libérait bien la mémoire alloué pour chaque image. (dans le cas d'un javaheap tardif)

2020-08-17 21:52 UTC, Vlammar commented on src/main/java/fr/moribus/imageonmap/image/PosterImage.java
> +            throw e;}
Pas ici, c'est uniquement si le rendu a eu un problème. cutImages peut prendre pas mal de Ram, et il peut y avoir lors de la découpe un manque de place. Cela remonte une exception, je m'assure dans ce cas de libérer la mémoire, le cas normal je ne libère pas la mémoire car on se sert plus tard de cutImages pour le rendu.

2020-08-17 21:53 UTC, Vlammar commented on src/main/java/fr/moribus/imageonmap/commands/maptool/GiveCommand.java
> +                }
Du coup on ne remonte pas à l'utilisateur l'information que le player map store n'a pas été trouvé ?

2020-08-17 21:56 UTC, Vlammar commented on src/main/java/fr/moribus/imageonmap/image/ImageRendererExecutor.java
> +        ImageIOExecutor.saveImage(mapID,image);
Une erreur qui a été corrigé par la PR de Pugabyte #112 mais que j'avais détecté et ajouté au code sans voir que le bug était présent sur indev

2020-08-17 21:57 UTC, AmauryCarrade commented on src/main/java/fr/moribus/imageonmap/commands/maptool/GiveCommand.java
> +                }
Ce code ne remonte pas cette info, mais uniquement celle que le _joueur_ n'a pas été trouvé. Or c'est déjà fait par `getPlayerParameter` qui envoie une erreur si le joueur n'est pas trouvé.

https://github.com/zDevelopers/zLib/blob/cb43ab335154738947d647b7d3c9e3a84996b180/src/main/java/fr/zcraft/zlib/components/commands/Command.java#L780-L790

Au passage, l'implémentation actuelle (la tienne ou celle via `getPlayerParameter`, elles sont équivalentes) ne permettent que de donner une carte appartenant à un joueur _actuellement connecté_. C'est voulu ?

2020-08-17 21:58 UTC, AmauryCarrade commented on src/main/java/fr/moribus/imageonmap/image/ImageUtils.java
> +//import java.awt.*;
Oui c'est ce que je dis faut retirer le commentaire :p 

```suggestion
```

2020-08-17 21:59 UTC, AmauryCarrade commented on src/main/java/fr/moribus/imageonmap/image/ImageUtils.java
> +            throw e;
D'accord. À retirer, alors :) .

2020-08-17 21:59 UTC, AmauryCarrade commented on src/main/java/fr/moribus/imageonmap/image/PosterImage.java
> +            throw e;}
D'accord.

2020-08-17 21:59 UTC, AmauryCarrade commented on src/main/java/fr/moribus/imageonmap/image/ImageRendererExecutor.java
> +        ImageIOExecutor.saveImage(mapID,image);
D'accord !

2020-08-21 15:46 UTC, Vlammar reviewed
@AmauryCarrade J'ai fais les différentes modifications requises, il reste l'histoire du worker et peut être l'aide pour les commandes à revoir

2020-08-21 15:46 UTC, Vlammar commented on src/main/java/fr/moribus/imageonmap/image/ImageUtils.java
> +//import java.awt.*;
Pas que le commentaire, l'import ne sert à rien ici

2020-08-21 15:46 UTC, Vlammar commented on src/main/java/fr/moribus/imageonmap/commands/maptool/GiveCommand.java
> +                }
Voulu oui, la raison est simple, je n'ai pas encore de méthode pour obtenir un joueur déconnecté. J'ai eu besoin d'en faire une pour la branche feature_NewCommand_for_non_player qui permet de créer des carte pour un joueur donné. Donc c'est à changer, ajout dans Zlib de getOfflinePlayerParameter ou d'une méthode qui retourne un joueur même si non connecté en passant par les services de mojang  ? (pas fan du nom car offlineplayer désigne autre chose)

2020-12-09 20:59 UTC, merged