Command rewrite
zDevelopers/ImageOnMap pull request #135
Opened 2020-12-12 13:06 UTC by Vlammar

Code need a cleanup espacially commands that need to be rewrited .

2020-12-13 14:50 UTC, Vlammar commented
When a target name is needed use prefixes like Vlammar:"Name of the map of Vlammar" instead of Vlammar "Name of the map of Vlammar"

2021-01-12 22:47 UTC, Vlammar commented
Commands can be cast on a terminal (with the exception of list,explore,new,delete,get,getremaining

2021-02-04 12:22 UTC, AmauryCarrade requested changes
Beaucoup beaucoup de remarques car tu réinventes pas mal la roue. Y'a aussi pas mal de choses qui mériteraient d'être factorisées, comme `NewCommand` et `UpdateCommand` qui sont assez proches.

Vivement le nouveau système de commandes qui permettra d'avoir des commandes _beaucoup_ plus propres, là c'est un peu le bordel avec tous ces arguments traités douze fois à l'ancienne. En attendant ça fait le job.

2021-02-04 12:22 UTC, AmauryCarrade commented on src/main/java/fr/moribus/imageonmap/commands/maptool/DeleteCommand.java
> +        //TODO passer en static
TODO à résoudre avant 4.1 ?

2021-02-04 12:22 UTC, AmauryCarrade commented on src/main/java/fr/moribus/imageonmap/commands/maptool/DeleteCommand.java
> +                MapManager.clear(sender.getInventory(), map);
Vu qu'on est en asynchrone, vérifier que le `sender` est toujours en ligne ferait sens (ça, ou la non-nullité de l'inventaire, ou les deux).

2021-02-04 12:22 UTC, AmauryCarrade commented on src/main/java/fr/moribus/imageonmap/commands/maptool/ExploreCommand.java
> +            Gui.open(sender, new MapListGui(offlinePlayer,playerName));
Idem, ajouter un `if (sender.isOnline())` ne mangerait pas de pain.

```suggestion
            if (sender.isOnline()) {
                Gui.open(sender, new MapListGui(offlinePlayer,playerName));
            }
```

2021-02-04 12:22 UTC, AmauryCarrade commented on src/main/java/fr/moribus/imageonmap/commands/maptool/GetCommand.java
> +                info(sender, I.t("The player {0} does not exist.", playerName));
```suggestion
                warning(sender, I.t("The player {0} does not exist.", playerName));
```

2021-02-04 12:22 UTC, AmauryCarrade commented on src/main/java/fr/moribus/imageonmap/commands/maptool/GetCommand.java
> +                info(sender, I.t("This map does not exist."));
```suggestion
                warning(sender, I.t("This map does not exist."));
```

2021-02-04 12:22 UTC, AmauryCarrade commented on src/main/java/fr/moribus/imageonmap/commands/maptool/GetCommand.java
> +                info(sender, I.t("You can't use this command"));
```suggestion
                throwNotAuthorized();
```

2021-02-04 12:22 UTC, AmauryCarrade commented on src/main/java/fr/moribus/imageonmap/commands/maptool/GetCommand.java
> +            warning(I.t("Too few parameters! Usage: /maptool get [playername]:<mapname>"));
Idem
```suggestion
            throwInvalidArgument(I.t("Too few parameters!"));
```

2021-02-04 12:22 UTC, AmauryCarrade commented on src/main/java/fr/moribus/imageonmap/commands/maptool/GetCommand.java
> +            warning(I.t("Too many parameters! Usage: /maptool get [playername]:<mapname>"));
Plus usage dans `@CommandInfo`
```suggestion
            throwInvalidArgument(I.t("Too many parameters!"));
```

2021-02-04 12:22 UTC, AmauryCarrade commented on src/main/java/fr/moribus/imageonmap/commands/maptool/ExploreCommand.java
> +            warning(I.t("Too many parameters! Usage: /maptool explore [playername]"));
Aussi ajouter l'usage à `@CommandInfo` (idem que plus haut je ne peux le suggérer).
```suggestion
            throwInvalidArgument(I.t("Too many parameters!"));
```

2021-02-04 12:22 UTC, AmauryCarrade commented on src/main/java/fr/moribus/imageonmap/commands/maptool/ExploreCommand.java
> +                info(sender, I.t("You can't use this command"));
```suggestion
                throwNotAuthorized();
```

2021-02-04 12:22 UTC, AmauryCarrade commented on src/main/java/fr/moribus/imageonmap/commands/maptool/ExploreCommand.java
> +                info(sender, I.t("The player {0} does not exist.", playerName));
```suggestion
                warning(sender, I.t("The player {0} does not exist.", playerName));
```

2021-02-04 12:22 UTC, AmauryCarrade commented on src/main/java/fr/moribus/imageonmap/commands/maptool/DeleteCommand.java
> +                    info(sender, I.t("Map successfully deleted."));
```suggestion
                    success(sender, I.t("Map successfully deleted."));
```

2021-02-04 12:22 UTC, AmauryCarrade commented on src/main/java/fr/moribus/imageonmap/commands/maptool/DeleteCommand.java
> +                info(sender, I.t("This map does not exist."));
```suggestion
                warning(sender, I.t("This map does not exist."));
```

2021-02-04 12:22 UTC, AmauryCarrade commented on src/main/java/fr/moribus/imageonmap/commands/maptool/DeleteCommand.java
> +                info(sender, I.t("The player {0} does not exist.", playerName));
```suggestion
                warning(sender, I.t("The player {0} does not exist.", playerName));
```

2021-02-04 12:22 UTC, AmauryCarrade commented on src/main/java/fr/moribus/imageonmap/commands/maptool/DeleteCommand.java
> +                info(sender, I.t("You can't use this command"));
```suggestion
                throwNotAuthorized();
```

2021-02-04 12:22 UTC, AmauryCarrade commented on src/main/java/fr/moribus/imageonmap/commands/maptool/DeleteCommand.java
> +            warning(I.t("Too few parameters! Usage: /maptool delete [playername]:<mapname>"));
```suggestion
            throwInvalidArgument(I.t("Too few parameters!"));
```

2021-02-04 12:22 UTC, AmauryCarrade commented on src/main/java/fr/moribus/imageonmap/commands/maptool/DeleteCommand.java
> +            warning(I.t("Too many parameters! Usage: /maptool delete [playername]:<mapname>"));
Aussi pas besoin de préciser l'usage, juste le message d'erreur. QuartzLib rappelle l'usage dans le message d'argument invalide. Il faut cela dit le mettre à jour dans `@CommandInfo`. Je me peux ajouter de suggestion en ce sens car c'est hors du diff, GitHub ne m'offre pas l'option.

```suggestion
            throwInvalidArgument(I.t("Too many parameters!"));
```

2021-02-04 12:22 UTC, AmauryCarrade commented on src/main/java/fr/moribus/imageonmap/commands/maptool/GiveCommand.java
> +            warning(I.t("Too many parameters! Usage: /maptool give <playername> [playerFrom]:<mapname>"));
```suggestion
            throwInvalidArgument(I.t("Too many parameters!"));
```

2021-02-04 12:22 UTC, AmauryCarrade commented on src/main/java/fr/moribus/imageonmap/commands/maptool/GiveCommand.java
> +            warning(I.t("Too few parameters! Usage: /maptool give <playername> [playerFrom]:<mapname>"));
```suggestion
            throwInvalidArgument(I.t("Too few parameters!"));
```

2021-02-04 12:22 UTC, AmauryCarrade commented on src/main/java/fr/moribus/imageonmap/commands/maptool/ListCommand.java
> +            warning(I.t("Too many parameters! Usage: /maptool list [playername]"));
```suggestion
            throwInvalidArgument(I.t("Too many parameters!"));
```

2021-02-04 12:22 UTC, AmauryCarrade commented on src/main/java/fr/moribus/imageonmap/commands/maptool/ListCommand.java
> +                info(sender, I.t("You can't use this command"));
```suggestion
                throwNotAuthorized();
```

2021-02-04 12:22 UTC, AmauryCarrade commented on src/main/java/fr/moribus/imageonmap/commands/maptool/ListCommand.java
> +                info(sender, I.t("Player {} not found.", playerName));
`error` ou `invalidArgument`.

2021-02-04 12:22 UTC, AmauryCarrade commented on src/main/java/fr/moribus/imageonmap/commands/maptool/ListCommand.java
> +                info(sender, I.t("No map found."));
`error` ou `invalidArgument`.

2021-02-04 12:22 UTC, AmauryCarrade commented on src/main/java/fr/moribus/imageonmap/commands/maptool/ListCommand.java
> +            RawMessage.send(sender, rawText.build());
Ne serait-il pas pertinent d'utiliser le module de pagination de chat ?

2021-02-04 12:22 UTC, AmauryCarrade commented on src/main/java/fr/moribus/imageonmap/commands/maptool/UpdateCommand.java
> +        }
Quel est l'intérêt de la variable `warningMsg` ?

Aussi, `error` ou `invalidArgument`.

2021-02-04 12:22 UTC, AmauryCarrade commented on src/main/java/fr/moribus/imageonmap/commands/maptool/UpdateCommand.java
> +            PluginLogger.warning("Usage: /maptool update [player name]:<map name> <new url> [stretched|covered]");
`throwInvalidArgument` (qui utilisera `sender` et l'enverra à la console si c'est pas un joueur)
```suggestion
            throwInvalidArgument("Usage: /maptool update [player name]:<map name> <new url> [stretched|covered]");
```

2021-02-04 12:22 UTC, AmauryCarrade commented on src/main/java/fr/moribus/imageonmap/commands/maptool/UpdateCommand.java
>  public class UpdateCommand extends IoMCommand {
Sans dire qu'il faut le faire maintenant je pense qu'il y a moyen de fusionner une partie du code (la logique de traitement des arguments) avec `NewCommand`.

2021-02-04 12:22 UTC, AmauryCarrade commented on src/main/java/fr/moribus/imageonmap/commands/maptool/UpdateCommand.java
> +                }
Idem pas de séparation entre les cas. Et idem sur `finalSender`.
```suggestion
                warning(sender, I.t("This map does not exist."));
```

2021-02-04 12:22 UTC, AmauryCarrade commented on src/main/java/fr/moribus/imageonmap/commands/maptool/UpdateCommand.java
> +                //assert size != null;
Commentaire superflu

2021-02-04 12:22 UTC, AmauryCarrade commented on src/main/java/fr/moribus/imageonmap/commands/maptool/UpdateCommand.java
> +                //TODO replace by a check of the load status.(if not loaded load the mapmanager)
TODO à faire avant la 4.1 ?

2021-02-04 12:22 UTC, AmauryCarrade commented on src/main/java/fr/moribus/imageonmap/commands/maptool/UpdateCommand.java
> +                }
Idem + `finalSender`

```suggestion
                warning(sender, I.t("Invalid URL."));
```

2021-02-04 12:22 UTC, AmauryCarrade commented on src/main/resources/plugin.yml
> +      imageonmap.deleteother: true
La description de ce groupe de permissions étant

> Grants all the user permissions (excluding administrative ones)

…je laisserais cette permission à `false`.

```suggestion
      imageonmap.deleteother: false
```

2021-02-04 12:22 UTC, AmauryCarrade commented on src/main/resources/plugin.yml
> +      imageonmap.updateother: true
Idem
```suggestion
      imageonmap.updateother: false
```

2021-02-04 12:22 UTC, AmauryCarrade commented on src/main/java/fr/moribus/imageonmap/commands/maptool/UpdateCommand.java
> +                    info(playerSender, I.t("You can't use this command"));
```suggestion
                    throwNotAuthorized();
```

2021-02-04 12:22 UTC, AmauryCarrade commented on src/main/java/fr/moribus/imageonmap/commands/maptool/UpdateCommand.java
> +                            info(playerSender, I.t("You can't use this command"));
```suggestion
                            throwNotAuthorized();
```

2021-02-04 12:22 UTC, AmauryCarrade commented on src/main/java/fr/moribus/imageonmap/commands/maptool/UpdateCommand.java
> +                        if (playerSender != null && !Permissions.UPDATEOTHER.grantedTo(playerSender)) {
`grantedTo` accepte un `Permissible`, ce qu'est un `CommandSender`.
```suggestion
                        if (!Permissions.UPDATEOTHER.grantedTo(sender)) {
```

2021-02-04 12:22 UTC, AmauryCarrade commented on src/main/java/fr/moribus/imageonmap/commands/maptool/UpdateCommand.java
> +                if (playerSender != null && !Permissions.UPDATEOTHER.grantedTo(playerSender)) {
`grantedTo` accepte un `Permissible`, ce qu'est un `CommandSender`.
```suggestion
                if (!Permissions.UPDATEOTHER.grantedTo(sender)) {
```

2021-02-04 12:22 UTC, AmauryCarrade commented on src/main/java/fr/moribus/imageonmap/commands/maptool/UpdateCommand.java
> +                }
Comme on ne peut utiliser `error` ou `throwInvalidArgument` que directement et pas dans un callback (car ça lance une exception, en fait). Et que `warning` accepte un `CommandSender`, qui fonctionne autant pour un joueur qu'une console (ou un bloc de commandes ou n'importe quoi d'autre comme une commande exécutée depuis rcon ou Discord).

Ne pas oublier qu'il y a plus que juste ou un joueur, ou la console.

Cette suggestion demande potentiellement d'ajouter avant l'appel à `offlineNameFetch` quelque chose du genre

```java
final CommandSender finalSender = sender;
```

…et d'utiliser `finalSender` à la place.

```suggestion
                warning(sender, I.t("The player {0} does not exist.", playerName));
```

2021-02-04 12:22 UTC, AmauryCarrade commented on src/main/java/fr/moribus/imageonmap/commands/maptool/GetCommand.java
> +        ImageOnMap.getPlugin().getCommandWorker().offlineNameFetch(playerName, uuid -> {
Sait-on jamais qu'iel se soit déconnecté⋅e entre temps
```suggestion
        ImageOnMap.getPlugin().getCommandWorker().offlineNameFetch(playerName, uuid -> {
            if (!sender.isOnline()) return;
```

2021-02-04 12:22 UTC, AmauryCarrade commented on src/main/java/fr/moribus/imageonmap/commands/maptool/GiveCommand.java
> +                throwInvalidArgument(I.t("Usage: /maptool give <playername> <playerFrom>:<mapname>"));
 `throwInvalidArgument` affiche la doc à l'utilisateur.
```suggestion
                throwInvalidArgument(I.t("Player name is required from the console"));
```

2021-02-04 12:22 UTC, AmauryCarrade commented on src/main/java/fr/moribus/imageonmap/commands/maptool/GiveCommand.java
> +                }
`finalSender` blablabla

```suggestion
                warning(sender, I.t("The player {0} does not exist.", from));
```

2021-02-04 12:22 UTC, AmauryCarrade commented on src/main/java/fr/moribus/imageonmap/commands/maptool/GiveCommand.java
> +                }
`finalSender` blahblahblah
```suggestion
                warning(sender, I.t("This map does not exist."));
```

2021-02-04 12:22 UTC, AmauryCarrade commented on src/main/java/fr/moribus/imageonmap/commands/maptool/GiveCommand.java
> +                    }
`finalSender`
```suggestion
                    warning(sender, I.t("The player {0} does not exist.", playerName));
```

2021-02-04 12:22 UTC, AmauryCarrade commented on src/main/java/fr/moribus/imageonmap/commands/maptool/GiveCommand.java
> +                }
Ou `finalSender`
```suggestion
                warning(sender, I.t("The player {0} does not exist.", playerName));
```

2021-02-04 17:18 UTC, Vlammar commented on src/main/resources/plugin.yml
> +      imageonmap.deleteother: true
Oui en effet petite coquille de ma part.

2021-02-04 17:18 UTC, Vlammar commented on src/main/resources/plugin.yml
> +      imageonmap.updateother: true
De même que précédemment

2021-02-04 17:18 UTC, Vlammar commented on src/main/java/fr/moribus/imageonmap/commands/maptool/DeleteCommand.java
> +            warning(I.t("Too many parameters! Usage: /maptool delete [playername]:<mapname>"));
Bon à savoir, j'ajoute ça sur le prochain comit

2021-02-04 17:18 UTC, Vlammar commented on src/main/java/fr/moribus/imageonmap/commands/maptool/DeleteCommand.java
> +        //TODO passer en static
Ce n'est pas bloquant, je ne suis pas sur de ce que ça apporte et du sens du static ici (Ca remonte à un moment, on en avait discuté). De mémoire c'était pour ne pas appeler le ImageOnMap.getPlugin().getCommandWorker()

2021-02-04 17:18 UTC, Vlammar commented on src/main/java/fr/moribus/imageonmap/commands/maptool/DeleteCommand.java
> +                MapManager.clear(sender.getInventory(), map);
Si `sender` est passe hors ligne pendant l'exécution sender reste évalué à != null, il est stocké en mémoire avec son inventaire ? Après ça ne coute rien d'ajouter le double test

2021-02-04 17:18 UTC, Vlammar commented on src/main/java/fr/moribus/imageonmap/commands/maptool/DeleteCommand.java
> +                    info(sender, I.t("Map successfully deleted."));
Je ne la connaissais pas cette dernière, merci du tip.

2021-02-04 17:18 UTC, Vlammar commented on src/main/java/fr/moribus/imageonmap/commands/maptool/ExploreCommand.java
> +            warning(I.t("Too many parameters! Usage: /maptool explore [playername]"));
C'est le cas pour presque toutes les commandes

2021-02-04 17:18 UTC, Vlammar commented on src/main/java/fr/moribus/imageonmap/commands/maptool/ListCommand.java
> +                info(sender, I.t("Player {} not found.", playerName));
Si tu cherche le joueur shqshdgsgucgfs (qui n'existe pas) tu auras ce message  mais ça peut aussi être un problème avec les services de Mojang qui ne marchent plus.

2021-02-04 17:18 UTC, Vlammar commented on src/main/java/fr/moribus/imageonmap/commands/maptool/ListCommand.java
> +            RawMessage.send(sender, rawText.build());
J'ai repris ce qui existait avant, tu parles du module avec un lien `Suivant` ?

2021-02-04 17:18 UTC, Vlammar commented on src/main/java/fr/moribus/imageonmap/commands/maptool/UpdateCommand.java
>  public class UpdateCommand extends IoMCommand {
Oui en effet j'ai pas mal de code dupliqué avec newCommand, j'attendais les nouvelles commande avant de le faire. Cette partie même fait sensiblement la même chose.

2021-02-04 17:18 UTC, Vlammar commented on src/main/java/fr/moribus/imageonmap/commands/maptool/UpdateCommand.java
> +        }
C'est une bonne question, c'est un invalidArgument ici :)

2021-02-04 17:18 UTC, Vlammar commented on src/main/java/fr/moribus/imageonmap/commands/maptool/UpdateCommand.java
> +                if (playerSender != null && !Permissions.UPDATEOTHER.grantedTo(playerSender)) {
Dans le cas de la console sender vaut null (de mémoire)

2021-02-04 17:18 UTC, Vlammar commented on src/main/java/fr/moribus/imageonmap/commands/maptool/UpdateCommand.java
> +                }
Pour moi CommanSender était forcément un humain... le if servait du coup pour savoir si on parle à une console ou un joueur

2021-02-04 17:18 UTC, Vlammar commented on src/main/java/fr/moribus/imageonmap/commands/maptool/UpdateCommand.java
> +                //TODO replace by a check of the load status.(if not loaded load the mapmanager)
C'était prévu pour la 4.2 quand je vais reprendre toute cette partie.

2021-02-04 17:18 UTC, Vlammar commented on src/main/java/fr/moribus/imageonmap/commands/maptool/UpdateCommand.java
> +                //assert size != null;
Yup

2021-02-05 15:58 UTC, Vlammar commented on src/main/java/fr/moribus/imageonmap/commands/maptool/UpdateCommand.java
> +        }
En fait c'est à cause de la limite en longueur du linter, sinon la ligne est trop longue et sauter une ligne il n'aime pas .

2021-02-07 11:40 UTC, Vlammar commented on src/main/java/fr/moribus/imageonmap/commands/maptool/ListCommand.java
> +                info(sender, I.t("No map found."));
Ce n'est pas une erreur pour ce cas là. C'est simplement que le joueur n'a pas de cartes.

2021-04-05 14:24 UTC, merged