Changed resize args.
zDevelopers/ImageOnMap pull request #170
Opened 2021-04-18 19:09 UTC by pierluigizagaria

I think that the "resize-" is just not neccessary and in this way the command is more fluent on the usage.

2021-04-18 21:52 UTC, Vlammar requested changes
Good idea, but leaving the old case is important. It's better to add the resize arguments than removing it. Can you put resize-stretched and resize-covered back? It can be nice to add stretched and covered.

2021-04-18 21:57 UTC, AmauryCarrade commented
I agree: I like your suggestion, it's way simpler, but as it's really easier to keep the old one we should keep them for compatibility.
Also we could add autocompletion with your arguments version only—I can explain how (it's really simple) if you want to.

2021-04-19 09:28 UTC, pierluigizagaria commented
I've tried to add the auto complete, but it seems to not work even on the original version.

2021-04-29 23:33 UTC, Vlammar approved these changes

2021-04-29 23:34 UTC, merged