add rename command to maptool
zDevelopers/ImageOnMap pull request #38
Opened 2017-10-06 16:52 UTC by jfmherokiller

This commit adds a rename to the maptool in order to allow the the user to rename the maps without going through the gui. This was done because the included library [zLib](https://github.com/zDevelopers/zLib) sometimes has issues pulling up the sign based gui.

2018-01-19 10:41 UTC, Adam759 commented
I wish the developers of this plugin were still around, this would be great functionality that would really complete this plugin. I may just recompile the jar with this change.

2018-01-24 00:37 UTC, AmauryCarrade commented
Hi! We're back.

I approve this functionality. I improved zLib's sign based GUI compatibility, but an alternative for thoses liking commands is always great.

The only problem with this PR is that _map names can include spaces_. A fix for this would be to allows to use quotation marks around the names, and to consider them without spaces it there isn't quotes. Like:

```
/maptool rename Map Map2
/maptool rename Map "Another name for the map"
/maptool rename "Another name for the map" "This one is better"
/maptool rename "This one is better" Better
```

Are you still interested in this or not?

2018-01-24 00:42 UTC, AmauryCarrade requested changes
A few notes on the code itself.

2018-01-24 00:42 UTC, AmauryCarrade commented on src/main/java/fr/moribus/imageonmap/ImageOnMap.java
> +import fr.moribus.imageonmap.commands.maptool.*;
Please avoir star imports :)

2018-01-24 00:42 UTC, AmauryCarrade commented on src/main/java/fr/moribus/imageonmap/commands/maptool/RenameCommand.java
> +            info("Not Enough Or To Many Arguments");
Please use the translations system: `info(I.t("Not enough or too many arguments"));`.

This comment is likely to become irrelevant for _this_ string if you fix the PR to support names with spaces, but it's a general comment on all strings displayed to a user :) .

2018-01-24 00:42 UTC, AmauryCarrade commented on src/main/java/fr/moribus/imageonmap/commands/maptool/RenameCommand.java
> +    }
Please add the permission check:

```java
@Override
public boolean canExecute(CommandSender sender)
{
    return Permissions.RENAME.grantedTo(sender);
}
```

2020-07-03 08:50 UTC, Vlammar commented on src/main/java/fr/moribus/imageonmap/commands/maptool/RenameCommand.java
> +    }
Added

2020-07-03 08:51 UTC, Vlammar commented on src/main/java/fr/moribus/imageonmap/ImageOnMap.java
> +import fr.moribus.imageonmap.commands.maptool.*;
Fixed, i have removed * import

2020-08-25 20:42 UTC, Vlammar commented
@AmauryCarrade I think we can do the merge, for the name with a space and the usage of " " for name with space.

2020-11-05 11:22 UTC, merged